// Art History Timeline Data
// Auto-generated from mappings

const ARTWORK_DATA = [
  {
    "id": "2.bezalel.intro.from the caves to civilization 2026_page_3_page3_img1",
    "title": "Nude woman (Venus of Willendorf), from Willendorf, Austria, ca. 28,000\u2013 25,000 BCE. Limestone,",
    "date_display": "ca. 28000-25000 BCE",
    "date_sort": -28000,
    "description": "",
    "era": "Prehistoric",
    "image_path": "images/2.bezalel.intro.from the caves to civilization 2026_page3_img1.jpeg",
    "presentation": "2.bezalel.intro.from the caves to civilization 2026",
    "page_number": ""
  },
  {
    "id": "2.bezalel.intro.from the caves to civilization 2026_page_8_page8_img1",
    "title": "Venus of Dolni Vestonice",
    "date_display": "29,000 - 25,000 BCE",
    "date_sort": -25000,
    "description": "",
    "era": "Prehistoric",
    "image_path": "images/2.bezalel.intro.from the caves to civilization 2026_page8_img1.jpeg",
    "presentation": "2.bezalel.intro.from the caves to civilization 2026",
    "page_number": ""
  },
  {
    "id": "2.bezalel.intro.from the caves to civilization 2026_page_8_page8_img3",
    "title": "Woman holding a bison horn",
    "date_display": "29,000 - 25,000 BCE",
    "date_sort": -25000,
    "description": "Laussel, Dordogne",
    "era": "Prehistoric",
    "image_path": "images/2.bezalel.intro.from the caves to civilization 2026_page8_img3.jpeg",
    "presentation": "2.bezalel.intro.from the caves to civilization 2026",
    "page_number": ""
  },
  {
    "id": "2.bezalel.intro.from the caves to civilization 2026_page_10_page10_img1",
    "title": "Hall of the Bulls (left wall), Lascaux, Dordogne, France, ca. 15,000\u201313,000 BCE.",
    "date_display": "ca. 15000-13000 BCE",
    "date_sort": -15000,
    "description": "",
    "era": "Prehistoric",
    "image_path": "images/2.bezalel.intro.from the caves to civilization 2026_page10_img1.jpeg",
    "presentation": "2.bezalel.intro.from the caves to civilization 2026",
    "page_number": ""
  },
  {
    "id": "2.bezalel.intro.from the caves to civilization 2026_page_12_page12_img1",
    "title": "Lascaux Cave",
    "date_display": "15,000 - 13,000 BCE",
    "date_sort": -15000,
    "description": "",
    "era": "Prehistoric",
    "image_path": "images/2.bezalel.intro.from the caves to civilization 2026_page12_img1.jpeg",
    "presentation": "2.bezalel.intro.from the caves to civilization 2026",
    "page_number": ""
  },
  {
    "id": "2.bezalel.intro.from the caves to civilization 2026_page_14_page14_img1",
    "title": "France, ca. 30,000\u201328,000 or ca. 15,000\u2013 13,000 BCE",
    "date_display": "ca. 15000-13000 BCE",
    "date_sort": -15000,
    "description": "",
    "era": "Prehistoric",
    "image_path": "images/2.bezalel.intro.from the caves to civilization 2026_page14_img1.jpeg",
    "presentation": "2.bezalel.intro.from the caves to civilization 2026",
    "page_number": ""
  },
  {
    "id": "2.bezalel.intro.from the caves to civilization 2026_page_14_page14_img2",
    "title": "France, ca. 30,000\u201328,000 or ca. 15,000\u2013 13,000 BCE",
    "date_display": "ca. 15000-13000 BCE",
    "date_sort": -15000,
    "description": "",
    "era": "Prehistoric",
    "image_path": "images/2.bezalel.intro.from the caves to civilization 2026_page14_img2.jpeg",
    "presentation": "2.bezalel.intro.from the caves to civilization 2026",
    "page_number": ""
  },
  {
    "id": "2.bezalel.intro.from the caves to civilization 2026_page_14_page14_img3",
    "title": "France, ca. 30,000\u201328,000 or ca. 15,000\u2013 13,000 BCE",
    "date_display": "ca. 15000-13000 BCE",
    "date_sort": -15000,
    "description": "",
    "era": "Prehistoric",
    "image_path": "images/2.bezalel.intro.from the caves to civilization 2026_page14_img3.jpeg",
    "presentation": "2.bezalel.intro.from the caves to civilization 2026",
    "page_number": ""
  },
  {
    "id": "2.bezalel.intro.from the caves to civilization 2026_page_19_page19_img1",
    "title": "White Temple and ziggurat, Uruk (modern Warka), Iraq, ca. 3200\u20133000 BCE. Sumerian Civilization \u2013 city state of Sumer",
    "date_display": "ca. 3200-3000 BCE",
    "date_sort": -3200,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/2.bezalel.intro.from the caves to civilization 2026_page19_img1.jpeg",
    "presentation": "2.bezalel.intro.from the caves to civilization 2026",
    "page_number": ""
  },
  {
    "id": "2.bezalel.intro.from the caves to civilization 2026_page_21_page21_img1",
    "title": "White Temple and ziggurat, Uruk (modern Warka), Iraq, ca. 3200\u20133000 BCE.",
    "date_display": "ca. 3200-3000 BCE",
    "date_sort": -3200,
    "description": "Uruk",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/2.bezalel.intro.from the caves to civilization 2026_page21_img1.jpeg",
    "presentation": "2.bezalel.intro.from the caves to civilization 2026",
    "page_number": ""
  },
  {
    "id": "2.bezalel.intro.from the caves to civilization 2026_page_22_page22_img1",
    "title": "Uruk (modern Warka), Iraq, ca. 3200\u20133000 BCE (after S. E.",
    "date_display": "ca. 3200-3000 BCE",
    "date_sort": -3200,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/2.bezalel.intro.from the caves to civilization 2026_page22_img1.jpeg",
    "presentation": "2.bezalel.intro.from the caves to civilization 2026",
    "page_number": ""
  },
  {
    "id": "2.bezalel.intro.from the caves to civilization 2026_page_17_page17_img1",
    "title": "Proto-Cuneiform tablet",
    "date_display": "3100 - 2900 BCE",
    "date_sort": -3100,
    "description": "",
    "era": "Prehistoric",
    "image_path": "images/2.bezalel.intro.from the caves to civilization 2026_page17_img1.jpeg",
    "presentation": "2.bezalel.intro.from the caves to civilization 2026",
    "page_number": ""
  },
  {
    "id": "1.bezalel.intro 2026_page_3_page3_img2",
    "title": "Mesopotamian Art 3000 BC",
    "date_display": "3000 BCE",
    "date_sort": -3000,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/1.bezalel.intro 2026_page3_img2.jpeg",
    "presentation": "1.bezalel.intro 2026",
    "page_number": ""
  },
  {
    "id": "3.bezalel.intro.mesopotamian.egyptian 2026_page_15_page15_img1",
    "title": "Palette of King Narmer (left, back; right, front), from Hierakonpolis, Egypt, Predynastic, ca. 3000\u20132920 BCE. Slate, Egyptian Museum,",
    "date_display": "ca. 3000-2920 BCE",
    "date_sort": -3000,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/3.bezalel.intro.mesopotamian.egyptian 2026_page15_img1.jpeg",
    "presentation": "3.bezalel.intro.mesopotamian.egyptian 2026",
    "page_number": ""
  },
  {
    "id": "2.bezalel.intro.from the caves to civilization 2026_page_24_page24_img2",
    "title": "Temple at Eshnunna (modern Tell Asmar), Iraq, ca. 2700 BCE. Gypsum inlaid with shell and",
    "date_display": "2700 BCE",
    "date_sort": -2700,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/2.bezalel.intro.from the caves to civilization 2026_page24_img2.jpeg",
    "presentation": "2.bezalel.intro.from the caves to civilization 2026",
    "page_number": ""
  },
  {
    "id": "4.bezalel.intro.mesopotamian.egyptian 2026_page_13_page13_img4",
    "title": "Saqqara, 2680 BC",
    "date_display": "2680 BCE",
    "date_sort": -2680,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/4.bezalel.intro.mesopotamian.egyptian 2026_page13_img4.jpeg",
    "presentation": "4.bezalel.intro.mesopotamian.egyptian 2026",
    "page_number": ""
  },
  {
    "id": "4.bezalel.intro.mesopotamian.egyptian 2026_page_20_page20_img2",
    "title": "Funerary sculpture of Djoser",
    "date_display": "2680 BCE",
    "date_sort": -2680,
    "description": "Saqqara",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/4.bezalel.intro.mesopotamian.egyptian 2026_page20_img2.jpeg",
    "presentation": "4.bezalel.intro.mesopotamian.egyptian 2026",
    "page_number": ""
  },
  {
    "id": "4.bezalel.intro.mesopotamian.egyptian 2026_page_25_page25_img1",
    "title": "Wooden panel from the mastaba tomb of Hesire, Dynasty III, 2675- 2625 BC",
    "date_display": "2675-2625 BCE",
    "date_sort": -2675,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/4.bezalel.intro.mesopotamian.egyptian 2026_page25_img1.jpeg",
    "presentation": "4.bezalel.intro.mesopotamian.egyptian 2026",
    "page_number": ""
  },
  {
    "id": "4.bezalel.intro.mesopotamian.egyptian 2026_page_8_page8_img1",
    "title": "Djoser, Saqqara, Egypt, Dynasty III, ca. 2630\u20132611 BCE.",
    "date_display": "ca. 2630-2611 BCE",
    "date_sort": -2630,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/4.bezalel.intro.mesopotamian.egyptian 2026_page8_img1.jpeg",
    "presentation": "4.bezalel.intro.mesopotamian.egyptian 2026",
    "page_number": ""
  },
  {
    "id": "4.bezalel.intro.mesopotamian.egyptian 2026_page_11_page11_img1",
    "title": "Egypt, Dynasty III, ca. 2630\u20132611 BCE.",
    "date_display": "ca. 2630-2611 BCE",
    "date_sort": -2630,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/4.bezalel.intro.mesopotamian.egyptian 2026_page11_img1.jpeg",
    "presentation": "4.bezalel.intro.mesopotamian.egyptian 2026",
    "page_number": ""
  },
  {
    "id": "4.bezalel.intro.mesopotamian.egyptian 2026_page_12_page12_img1",
    "title": "Facade of the North Palace of the mortuary precinct of Djoser",
    "date_display": "2630\u20132611 BCE",
    "date_sort": -2630,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/4.bezalel.intro.mesopotamian.egyptian 2026_page12_img1.jpeg",
    "presentation": "4.bezalel.intro.mesopotamian.egyptian 2026",
    "page_number": ""
  },
  {
    "id": "2.bezalel.intro.from the caves to civilization 2026_page_26_page26_img1",
    "title": "Standing Male Worshiper",
    "date_display": "2900 - 2600 BCE",
    "date_sort": -2600,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/2.bezalel.intro.from the caves to civilization 2026_page26_img1.jpeg",
    "presentation": "2.bezalel.intro.from the caves to civilization 2026",
    "page_number": ""
  },
  {
    "id": "2.bezalel.intro.from the caves to civilization 2026_page_28_page28_img1",
    "title": "Cemetery, Ur (modern Tell Muqayyar), Iraq, ca. 2600 BCE.",
    "date_display": "2600 BCE",
    "date_sort": -2600,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/2.bezalel.intro.from the caves to civilization 2026_page28_img1.jpeg",
    "presentation": "2.bezalel.intro.from the caves to civilization 2026",
    "page_number": ""
  },
  {
    "id": "2.bezalel.intro.from the caves to civilization 2026_page_29_page29_img1",
    "title": "Tell Muqayyar), Iraq, ca. 2600 BCE. Wood inlaid with shell, lapis lazuli, and red",
    "date_display": "2600 BCE",
    "date_sort": -2600,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/2.bezalel.intro.from the caves to civilization 2026_page29_img1.jpeg",
    "presentation": "2.bezalel.intro.from the caves to civilization 2026",
    "page_number": ""
  },
  {
    "id": "2.bezalel.intro.from the caves to civilization 2026_page_30_page30_img1",
    "title": "War side of the Standard of Ur",
    "date_display": "2600 BCE",
    "date_sort": -2600,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/2.bezalel.intro.from the caves to civilization 2026_page30_img1.jpeg",
    "presentation": "2.bezalel.intro.from the caves to civilization 2026",
    "page_number": ""
  },
  {
    "id": "2.bezalel.intro.from the caves to civilization 2026_page_33_page33_img1",
    "title": "Peace side of the Standard of Ur, from Tomb 779, Royal Cemetery, Ur (modern Tell Muqayyar), Iraq, ca. 2600 BCE. Wood inlaid with shell, lapis",
    "date_display": "2600 BCE",
    "date_sort": -2600,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/2.bezalel.intro.from the caves to civilization 2026_page33_img1.jpeg",
    "presentation": "2.bezalel.intro.from the caves to civilization 2026",
    "page_number": ""
  },
  {
    "id": "4.bezalel.intro.mesopotamian.egyptian 2026_page_15_page15_img1",
    "title": "Great Pyramids, Gizeh, Egypt, Dynasty IV. From left: Pyramids of Menkaure, ca. 2490\u20132472 BCE; Khafre, ca. 2520\u20132494 BCE; and Khufu, ca. 2551\u20132528 BCE.",
    "date_display": "ca. 2551-2528 BCE",
    "date_sort": -2551,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/4.bezalel.intro.mesopotamian.egyptian 2026_page15_img1.jpeg",
    "presentation": "4.bezalel.intro.mesopotamian.egyptian 2026",
    "page_number": ""
  },
  {
    "id": "4.bezalel.intro.mesopotamian.egyptian 2026_page_18_page18_img1",
    "title": "Great Sphinx (with Pyramid of Khafre in the background at left), Gizeh, Egypt, Dynasty IV, ca. 2520\u20132494 BCE.",
    "date_display": "ca. 2520-2494 BCE",
    "date_sort": -2520,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/4.bezalel.intro.mesopotamian.egyptian 2026_page18_img1.jpeg",
    "presentation": "4.bezalel.intro.mesopotamian.egyptian 2026",
    "page_number": ""
  },
  {
    "id": "4.bezalel.intro.mesopotamian.egyptian 2026_page_19_page19_img2",
    "title": "Dynasty IV, ca. 2520\u20132494 BCE. Diorite, Egyptian",
    "date_display": "ca. 2520-2494 BCE",
    "date_sort": -2520,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/4.bezalel.intro.mesopotamian.egyptian 2026_page19_img2.jpeg",
    "presentation": "4.bezalel.intro.mesopotamian.egyptian 2026",
    "page_number": ""
  },
  {
    "id": "4.bezalel.intro.mesopotamian.egyptian 2026_page_23_page23_img1",
    "title": "Menkaure and Khamerernebty (?), from Gizeh, Egypt, Dynasty IV, ca. 2490\u20132472 BCE. Graywacke,",
    "date_display": "ca. 2490-2472 BCE",
    "date_sort": -2490,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/4.bezalel.intro.mesopotamian.egyptian 2026_page23_img1.jpeg",
    "presentation": "4.bezalel.intro.mesopotamian.egyptian 2026",
    "page_number": ""
  },
  {
    "id": "4.bezalel.intro.mesopotamian.egyptian 2026_page_23_page23_img2",
    "title": "Menkaure and Khamerernebty (?), from Gizeh, Egypt, Dynasty IV, ca. 2490\u20132472 BCE. Graywacke,",
    "date_display": "ca. 2490-2472 BCE",
    "date_sort": -2490,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/4.bezalel.intro.mesopotamian.egyptian 2026_page23_img2.jpeg",
    "presentation": "4.bezalel.intro.mesopotamian.egyptian 2026",
    "page_number": ""
  },
  {
    "id": "4.bezalel.intro.mesopotamian.egyptian 2026_page_24_page24_img1",
    "title": "Ti watching a hippopotamus hunt, relief in the mastaba of Ti, Saqqara, Egypt, Dynasty V, ca. 2450\u20132350 BCE. Painted limestone, hunting",
    "date_display": "ca. 2450-2350 BCE",
    "date_sort": -2450,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/4.bezalel.intro.mesopotamian.egyptian 2026_page24_img1.jpeg",
    "presentation": "4.bezalel.intro.mesopotamian.egyptian 2026",
    "page_number": ""
  },
  {
    "id": "3.bezalel.intro.mesopotamian.egyptian 2026_page_3_page3_img1",
    "title": "Victory stele of Naram-Sin",
    "date_display": "2254\u20132218 BCE",
    "date_sort": -2254,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/3.bezalel.intro.mesopotamian.egyptian 2026_page3_img1.jpeg",
    "presentation": "3.bezalel.intro.mesopotamian.egyptian 2026",
    "page_number": ""
  },
  {
    "id": "3.bezalel.intro.mesopotamian.egyptian 2026_page_10_page10_img3",
    "title": "Babylonian civilization \u2013 1800 BC",
    "date_display": "1800 BCE",
    "date_sort": -1800,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/3.bezalel.intro.mesopotamian.egyptian 2026_page10_img3.jpeg",
    "presentation": "3.bezalel.intro.mesopotamian.egyptian 2026",
    "page_number": ""
  },
  {
    "id": "3.bezalel.intro.mesopotamian.egyptian 2026_page_4_page4_img1",
    "title": "Stele with law code of Hammurabi",
    "date_display": "1780 BCE",
    "date_sort": -1780,
    "description": "",
    "era": "High Renaissance",
    "image_path": "images/3.bezalel.intro.mesopotamian.egyptian 2026_page4_img1.jpeg",
    "presentation": "3.bezalel.intro.mesopotamian.egyptian 2026",
    "page_number": ""
  },
  {
    "id": "3.bezalel.intro.mesopotamian.egyptian 2026_page_4_page4_img2",
    "title": "Stele with law code of Hammurabi",
    "date_display": "1780 BCE",
    "date_sort": -1780,
    "description": "",
    "era": "High Renaissance",
    "image_path": "images/3.bezalel.intro.mesopotamian.egyptian 2026_page4_img2.jpeg",
    "presentation": "3.bezalel.intro.mesopotamian.egyptian 2026",
    "page_number": ""
  },
  {
    "id": "6.intro.greek art.memesis_page_9_page9_img1",
    "title": "Proto-Dorian Columns, Mortuary Temple of Queen Hatshepsut, Deir el Bahri, 1490-1460 BC",
    "date_display": "1490-1460 BCE",
    "date_sort": -1490,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/6.intro.greek art.memesis_page9_img1.jpeg",
    "presentation": "6.intro.greek art.memesis",
    "page_number": ""
  },
  {
    "id": "4.bezalel.intro.mesopotamian.egyptian 2026_page_27_page27_img1",
    "title": "Karnak, Egypt, 18th Dynasty, ca. 1353\u20131335 BCE. Sandstone, Egyptian",
    "date_display": "ca. 1353-1335 BCE",
    "date_sort": -1353,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/4.bezalel.intro.mesopotamian.egyptian 2026_page27_img1.jpeg",
    "presentation": "4.bezalel.intro.mesopotamian.egyptian 2026",
    "page_number": ""
  },
  {
    "id": "4.bezalel.intro.mesopotamian.egyptian 2026_page_28_page28_img1",
    "title": "Akhenaton, Nefertiti, and three daughters, from Tell el-Amarna, Dynasty XVIII",
    "date_display": "ca. 1353-1335 BCE",
    "date_sort": -1353,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/4.bezalel.intro.mesopotamian.egyptian 2026_page28_img1.jpeg",
    "presentation": "4.bezalel.intro.mesopotamian.egyptian 2026",
    "page_number": ""
  },
  {
    "id": "4.bezalel.intro.mesopotamian.egyptian 2026_page_30_page30_img1",
    "title": "THUTMOSE, Nefertiti, from Tell el-Amarna, Egypt, Dynasty XVIII, ca. 1353\u20131335 BCE. Painted",
    "date_display": "ca. 1353-1335 BCE",
    "date_sort": -1353,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/4.bezalel.intro.mesopotamian.egyptian 2026_page30_img1.jpeg",
    "presentation": "4.bezalel.intro.mesopotamian.egyptian 2026",
    "page_number": ""
  },
  {
    "id": "6.intro.greek art.memesis_page_10_page10_img1",
    "title": "Hypostyle Hall, Temple of Amen-Re, Karnak, Egypt, 1290-1224 BC, Model by",
    "date_display": "1290-1224 BCE",
    "date_sort": -1290,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/6.intro.greek art.memesis_page10_img1.jpeg",
    "presentation": "6.intro.greek art.memesis",
    "page_number": ""
  },
  {
    "id": "4.bezalel.intro.mesopotamian.egyptian 2026_page_5_page5_img1",
    "title": "Detail from the Papyrus of Hunefer (Book of the Dead), 1275 BC,",
    "date_display": "1275 BCE",
    "date_sort": -1275,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/4.bezalel.intro.mesopotamian.egyptian 2026_page5_img1.jpeg",
    "presentation": "4.bezalel.intro.mesopotamian.egyptian 2026",
    "page_number": ""
  },
  {
    "id": "4.bezalel.intro.mesopotamian.egyptian 2026_page_6_page6_img1",
    "title": "Hunefer (Book of the Dead), 1275 BC, The British",
    "date_display": "1275 BCE",
    "date_sort": -1275,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/4.bezalel.intro.mesopotamian.egyptian 2026_page6_img1.jpeg",
    "presentation": "4.bezalel.intro.mesopotamian.egyptian 2026",
    "page_number": ""
  },
  {
    "id": "2.bezalel.intro.from the caves to civilization 2026_page_18_page18_img1",
    "title": "Cuneiform tablet",
    "date_display": "",
    "date_sort": -1000,
    "description": "",
    "era": "High Renaissance",
    "image_path": "images/2.bezalel.intro.from the caves to civilization 2026_page18_img1.jpeg",
    "presentation": "2.bezalel.intro.from the caves to civilization 2026",
    "page_number": ""
  },
  {
    "id": "3.bezalel.intro.mesopotamian.egyptian 2026_page_10_page10_img4",
    "title": "Assyrian civilization \u2013 900 BC",
    "date_display": "900 BCE",
    "date_sort": -900,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/3.bezalel.intro.mesopotamian.egyptian 2026_page10_img4.jpeg",
    "presentation": "3.bezalel.intro.mesopotamian.egyptian 2026",
    "page_number": ""
  },
  {
    "id": "5.intro.greek art.memesis_page_6_page6_img1",
    "title": "Dypilon Master, Geometric Amphora, 750 BC, 154",
    "date_display": "750 BCE",
    "date_sort": -750,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/5.intro.greek art.memesis_page6_img1.jpeg",
    "presentation": "5.intro.greek art.memesis",
    "page_number": ""
  },
  {
    "id": "5.intro.greek art.memesis_page_7_page7_img1",
    "title": "Dypilon Master, Geometric Amphora, 750 BC",
    "date_display": "750 BC",
    "date_sort": -750,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/5.intro.greek art.memesis_page7_img1.jpeg",
    "presentation": "5.intro.greek art.memesis",
    "page_number": ""
  },
  {
    "id": "5.intro.greek art.memesis_page_4_page4_img1",
    "title": "Dipylon Master, Geometric krater, from the Dipylon cemetery, Athens, Greece, ca. 740 BCE. 108 cm high, Metropolitan Museum of",
    "date_display": "740 BCE",
    "date_sort": -740,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/5.intro.greek art.memesis_page4_img1.jpeg",
    "presentation": "5.intro.greek art.memesis",
    "page_number": ""
  },
  {
    "id": "3.bezalel.intro.mesopotamian.egyptian 2026_page_6_page6_img1",
    "title": "Lamassu (winged, human- headed bull), from the citadel of Sargon II, Dur Sharrukin (modern Khorsabad), Iraq, ca. 720\u2013705 BCE. Limestone,",
    "date_display": "ca. 720-705 BCE",
    "date_sort": -720,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/3.bezalel.intro.mesopotamian.egyptian 2026_page6_img1.jpeg",
    "presentation": "3.bezalel.intro.mesopotamian.egyptian 2026",
    "page_number": ""
  },
  {
    "id": "2.bezalel.intro.from the caves to civilization 2026_page_19_page19_img2",
    "title": "Gilgamesh",
    "date_display": "8th century BCE",
    "date_sort": -700,
    "description": "Khorshabad",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/2.bezalel.intro.from the caves to civilization 2026_page19_img2.jpeg",
    "presentation": "2.bezalel.intro.from the caves to civilization 2026",
    "page_number": ""
  },
  {
    "id": "5.intro.greek art.memesis_page_9_page9_img1",
    "title": "Lady of Auxerre, statue of a goddess or kore, ca. 650\u2013625 BCE. 75 cm, Limestone, Louvre,",
    "date_display": "ca. 650-625 BCE",
    "date_sort": -650,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/5.intro.greek art.memesis_page9_img1.jpeg",
    "presentation": "5.intro.greek art.memesis",
    "page_number": ""
  },
  {
    "id": "5.intro.greek art.memesis_page_10_page10_img1",
    "title": "Kouros, ca. 600 BCE. 194 cm, Marble,",
    "date_display": "600 BCE",
    "date_sort": -600,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/5.intro.greek art.memesis_page10_img1.jpeg",
    "presentation": "5.intro.greek art.memesis",
    "page_number": ""
  },
  {
    "id": "5.intro.greek art.memesis_page_12_page12_img1",
    "title": "Kouros, ca. 600 BCE. 194 cm,",
    "date_display": "600 BCE",
    "date_sort": -600,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/5.intro.greek art.memesis_page12_img1.jpeg",
    "presentation": "5.intro.greek art.memesis",
    "page_number": ""
  },
  {
    "id": "5.intro.greek art.memesis_page_12_page12_img2",
    "title": "Kouros, ca. 600 BCE. 194 cm,",
    "date_display": "600 BCE",
    "date_sort": -600,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/5.intro.greek art.memesis_page12_img2.jpeg",
    "presentation": "5.intro.greek art.memesis",
    "page_number": ""
  },
  {
    "id": "6.intro.greek art.memesis_page_14_page14_img1",
    "title": "West pediment from the Temple of Artemis, Corfu, Greece, ca. 600\u2013580 BCE.",
    "date_display": "ca. 600-580 BCE",
    "date_sort": -600,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/6.intro.greek art.memesis_page14_img1.jpeg",
    "presentation": "6.intro.greek art.memesis",
    "page_number": ""
  },
  {
    "id": "5.intro.greek art.memesis_page_13_page13_img1",
    "title": "Kroisos, from Anavysos, Greece, ca. 530 BCE.",
    "date_display": "530 BCE",
    "date_sort": -530,
    "description": "",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/5.intro.greek art.memesis_page13_img1.jpeg",
    "presentation": "5.intro.greek art.memesis",
    "page_number": ""
  },
  {
    "id": "7.greek late periods.roman_page_3_page3_img2",
    "title": "Peplos Kore, from the Acropolis, Athens,",
    "date_display": "530 BCE",
    "date_sort": -530,
    "description": "Acropolis, Athens",
    "era": "Ancient Near East & Egypt",
    "image_path": "images/7.greek late periods.roman_page3_img2.jpeg",
    "presentation": "7.greek late periods.roman",
    "page_number": ""
  },
  {
    "id": "6.intro.greek art.memesis_page_16_page16_img1",
    "title": "Temple of Aphaia, Aegina, Greece, ca. 500\u2013490 BCE.",
    "date_display": "ca. 500-490 BCE",
    "date_sort": -500,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/6.intro.greek art.memesis_page16_img1.jpeg",
    "presentation": "6.intro.greek art.memesis",
    "page_number": ""
  },
  {
    "id": "6.intro.greek art.memesis_page_17_page17_img1",
    "title": "West pediment of the Temple of Aphaia, Aegina, Greece, ca. 500-490 BCE. Marble, approx. 5\u2019 8\u201d high at center. Glyptothek, Munich.",
    "date_display": "ca. 500-490 BCE",
    "date_sort": -500,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/6.intro.greek art.memesis_page17_img1.jpeg",
    "presentation": "6.intro.greek art.memesis",
    "page_number": ""
  },
  {
    "id": "6.intro.greek art.memesis_page_18_page18_img1",
    "title": "Dying warrior, from the west pediment of the Temple of Aphaia, Aegina",
    "date_display": "ca. 500-490 BCE",
    "date_sort": -500,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/6.intro.greek art.memesis_page18_img1.jpeg",
    "presentation": "6.intro.greek art.memesis",
    "page_number": ""
  },
  {
    "id": "6.intro.greek art.memesis_page_19_page19_img1",
    "title": "Dying warrior, from the east pediment of the Temple of Aphaia, Aegina, Greece, ca. 490\u2013480 BCE. Marble, Glyptothek, Munich.",
    "date_display": "ca. 490-480 BCE",
    "date_sort": -490,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/6.intro.greek art.memesis_page19_img1.jpeg",
    "presentation": "6.intro.greek art.memesis",
    "page_number": ""
  },
  {
    "id": "5.intro.greek art.memesis_page_17_page17_img1",
    "title": "Kritios Boy, from the Acropolis, Athens, Greece, ca. 480 BCE. Marble, approx. 117 cm high.",
    "date_display": "480 BCE",
    "date_sort": -480,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/5.intro.greek art.memesis_page17_img1.jpeg",
    "presentation": "5.intro.greek art.memesis",
    "page_number": ""
  },
  {
    "id": "5.intro.greek art.memesis_page_18_page18_img1",
    "title": "Warrior, from the sea off Riace, Italy, ca. 460\u2013 450 BCE. Bronze, approx. 2 meters high.",
    "date_display": "ca. 460-450 BCE",
    "date_sort": -460,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/5.intro.greek art.memesis_page18_img1.jpeg",
    "presentation": "5.intro.greek art.memesis",
    "page_number": ""
  },
  {
    "id": "12.renaissance.intro_page_9_page9_img1",
    "title": "POLYKLEITOS, Doryphoros (Spear Bearer). Roman marble copy from Pompeii, Italy, after a bronze original of ca. 450\u2013440 BCE, 2.1 meters high. Museo Nazionale, Naples.",
    "date_display": "ca. 450-440 BCE",
    "date_sort": -450,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/12.renaissance.intro_page9_img1.jpeg",
    "presentation": "12.renaissance.intro",
    "page_number": ""
  },
  {
    "id": "6.intro.greek art.memesis_page_2_page2_img1",
    "title": "MYRON, Diskobolos (Discus Thrower). Roman marble copy after a bronze original of ca. 450 BCE",
    "date_display": "450 BCE",
    "date_sort": -450,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/6.intro.greek art.memesis_page2_img1.jpeg",
    "presentation": "6.intro.greek art.memesis",
    "page_number": ""
  },
  {
    "id": "6.intro.greek art.memesis_page_3_page3_img1",
    "title": "POLYKLEITOS, Doryphoros (Spear Bearer).",
    "date_display": "ca. 450-440 BCE",
    "date_sort": -450,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/6.intro.greek art.memesis_page3_img1.jpeg",
    "presentation": "6.intro.greek art.memesis",
    "page_number": ""
  },
  {
    "id": "6.intro.greek art.memesis_page_24_page24_img1",
    "title": "IKTINOS and KALLIKRATES, Parthenon, the Temple of Athena Parthenos (view from the northwest), Acropolis, Athens, Greece, 447\u2013438 BCE",
    "date_display": "447-438 BCE",
    "date_sort": -447,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/6.intro.greek art.memesis_page24_img1.jpeg",
    "presentation": "6.intro.greek art.memesis",
    "page_number": ""
  },
  {
    "id": "6.intro.greek art.memesis_page_29_page29_img1",
    "title": "Metopes from the southern side of the Parthenon",
    "date_display": "447 BCE",
    "date_sort": -447,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/6.intro.greek art.memesis_page29_img1.jpeg",
    "presentation": "6.intro.greek art.memesis",
    "page_number": ""
  },
  {
    "id": "6.intro.greek art.memesis_page_29_page29_img2",
    "title": "Metopes from the southern side of the Parthenon",
    "date_display": "",
    "date_sort": -447,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/6.intro.greek art.memesis_page29_img2.jpeg",
    "presentation": "6.intro.greek art.memesis",
    "page_number": ""
  },
  {
    "id": "6.intro.greek art.memesis_page_29_page29_img3",
    "title": "Metopes from the southern side of the Parthenon",
    "date_display": "",
    "date_sort": -447,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/6.intro.greek art.memesis_page29_img3.jpeg",
    "presentation": "6.intro.greek art.memesis",
    "page_number": ""
  },
  {
    "id": "6.intro.greek art.memesis_page_30_page30_img1",
    "title": "Athens, Greece, ca. 447\u2013438 BCE. Horsemen of north frieze (top), British Museum, London;",
    "date_display": "ca. 447-438 BCE",
    "date_sort": -447,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/6.intro.greek art.memesis_page30_img1.jpeg",
    "presentation": "6.intro.greek art.memesis",
    "page_number": ""
  },
  {
    "id": "6.intro.greek art.memesis_page_30_page30_img2",
    "title": "Athens, Greece, ca. 447\u2013438 BCE. Horsemen of north frieze (top), British Museum, London;",
    "date_display": "ca. 447-438 BCE",
    "date_sort": -447,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/6.intro.greek art.memesis_page30_img2.jpeg",
    "presentation": "6.intro.greek art.memesis",
    "page_number": ""
  },
  {
    "id": "6.intro.greek art.memesis_page_30_page30_img3",
    "title": "Athens, Greece, ca. 447\u2013438 BCE. Horsemen of north frieze (top), British Museum, London;",
    "date_display": "ca. 447-438 BCE",
    "date_sort": -447,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/6.intro.greek art.memesis_page30_img3.jpeg",
    "presentation": "6.intro.greek art.memesis",
    "page_number": ""
  },
  {
    "id": "6.intro.greek art.memesis_page_27_page27_img1",
    "title": "Parthenon, Acropolis, Athens, Greece, ca. 438 BCE. Model of the lost statue, which was approx. 11/5 meters tall. Royal Ontario",
    "date_display": "438 BCE",
    "date_sort": -438,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/6.intro.greek art.memesis_page27_img1.jpeg",
    "presentation": "6.intro.greek art.memesis",
    "page_number": ""
  },
  {
    "id": "6.intro.greek art.memesis_page_31_page31_img1",
    "title": "Helios and his horses, and Dionysos (Herakles?), from the east pediment of the Parthenon",
    "date_display": "ca. 438-432 BCE",
    "date_sort": -438,
    "description": "Acropolis, Greece",
    "era": "Classical Antiquity",
    "image_path": "images/6.intro.greek art.memesis_page31_img1.jpeg",
    "presentation": "6.intro.greek art.memesis",
    "page_number": ""
  },
  {
    "id": "6.intro.greek art.memesis_page_32_page32_img1",
    "title": "Three goddesses (Hestia, Dione, and Aphrodite?), from the east pediment of the Parthenon, Acropolis, Athens, Greece, ca. 438\u2013432 BCE. Marble,",
    "date_display": "ca. 438-432 BCE",
    "date_sort": -438,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/6.intro.greek art.memesis_page32_img1.jpeg",
    "presentation": "6.intro.greek art.memesis",
    "page_number": ""
  },
  {
    "id": "1.bezalel.intro 2026_page_3_page3_img4",
    "title": "Greece 5th c. BC",
    "date_display": "5th century BCE",
    "date_sort": -400,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/1.bezalel.intro 2026_page3_img4.jpeg",
    "presentation": "1.bezalel.intro 2026",
    "page_number": ""
  },
  {
    "id": "7.greek late periods.roman_page_3_page3_img1",
    "title": "PRAXITELES, Aphrodite of Knidos. Roman marble copy after an original of ca. 350\u2013340 BCE. Approx. 2.07 meters high. Vatican Museums, Rome",
    "date_display": "ca. 350-340 BCE",
    "date_sort": -350,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/7.greek late periods.roman_page3_img1.jpeg",
    "presentation": "7.greek late periods.roman",
    "page_number": ""
  },
  {
    "id": "7.greek late periods.roman_page_4_page4_img3",
    "title": "LYSIPPOS, Apoxyomenos (Scraper). Roman marble copy after a bronze original of ca. 330 BCE, approx. 2.10 meters high. Vatican Museums, Rome.",
    "date_display": "330 BCE",
    "date_sort": -330,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/7.greek late periods.roman_page4_img3.jpeg",
    "presentation": "7.greek late periods.roman",
    "page_number": ""
  },
  {
    "id": "7.greek late periods.roman_page_4_page4_img2",
    "title": "LYSIPPOS, Apoxyomenos (Scraper). Roman marble copy after a bronze original of ca. 330 BCE, approx. 2.10 meters high. Vatican Museums, Rome.",
    "date_display": "330 BCE",
    "date_sort": -330,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/7.greek late periods.roman_page4_img2.jpeg",
    "presentation": "7.greek late periods.roman",
    "page_number": ""
  },
  {
    "id": "7.greek late periods.roman_page_4_page4_img1",
    "title": "LYSIPPOS, Apoxyomenos (Scraper). Roman marble copy after a bronze original of ca. 330 BCE, approx. 2.10 meters high. Vatican Museums, Rome.",
    "date_display": "330 BCE",
    "date_sort": -330,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/7.greek late periods.roman_page4_img1.jpeg",
    "presentation": "7.greek late periods.roman",
    "page_number": ""
  },
  {
    "id": "7.greek late periods.roman_page_5_page5_img1",
    "title": "Lysippos, 330 BC",
    "date_display": "330 BCE",
    "date_sort": -330,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/7.greek late periods.roman_page5_img1.jpeg",
    "presentation": "7.greek late periods.roman",
    "page_number": ""
  },
  {
    "id": "7.greek late periods.roman_page_6_page6_img1",
    "title": "LYSIPPOS, Weary Herakles (Farnese Herakles). Roman marble copy from Rome, Italy, signed by GLYKON OF ATHENS, after a bronze original of ca. 320 BCE. Approx. 3.2 meters high.",
    "date_display": "320 BCE",
    "date_sort": -320,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/7.greek late periods.roman_page6_img1.jpeg",
    "presentation": "7.greek late periods.roman",
    "page_number": ""
  },
  {
    "id": "7.greek late periods.roman_page_6_page6_img2",
    "title": "LYSIPPOS, Weary Herakles (Farnese Herakles). Roman marble copy from Rome, Italy, signed by GLYKON OF ATHENS, after a bronze original of ca. 320 BCE. Approx. 3.2 meters high.",
    "date_display": "320 BCE",
    "date_sort": -320,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/7.greek late periods.roman_page6_img2.jpeg",
    "presentation": "7.greek late periods.roman",
    "page_number": ""
  },
  {
    "id": "7.greek late periods.roman_page_9_page9_img1",
    "title": "ATHANADOROS, HAGESANDROS, and POLYDOROS OF RHODES, Laoco\u00f6n and his sons, from Rome, Italy, 200 BC \u2013 70 AD (suggested), Marble, approx. 2.16 meters high. Vatican",
    "date_display": "200 BCE",
    "date_sort": -200,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/7.greek late periods.roman_page9_img1.jpeg",
    "presentation": "7.greek late periods.roman",
    "page_number": ""
  },
  {
    "id": "1.bezalel.intro 2026_page_9_page9_img2",
    "title": "Milo, 150-125 BC, Louvre, Paris",
    "date_display": "150-125 BCE",
    "date_sort": -150,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/1.bezalel.intro 2026_page9_img2.jpeg",
    "presentation": "1.bezalel.intro 2026",
    "page_number": ""
  },
  {
    "id": "7.greek late periods.roman_page_7_page7_img1",
    "title": "ALEXANDROS OF ANTIOCH-ON-THE-MEANDER, Aphrodite (Venus de Milo)",
    "date_display": "",
    "date_sort": -150,
    "description": "Melos, Greece",
    "era": "Classical Antiquity",
    "image_path": "images/7.greek late periods.roman_page7_img1.jpeg",
    "presentation": "7.greek late periods.roman",
    "page_number": ""
  },
  {
    "id": "7.greek late periods.roman_page_8_page8_img1",
    "title": "ALEXANDROS OF ANTIOCH-ON-THE-MEANDER, Aphrodite (Venus de Milo)",
    "date_display": "",
    "date_sort": -150,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/7.greek late periods.roman_page8_img1.jpeg",
    "presentation": "7.greek late periods.roman",
    "page_number": ""
  },
  {
    "id": "7.greek late periods.roman_page_8_page8_img2",
    "title": "ALEXANDROS OF ANTIOCH-ON-THE-MEANDER, Aphrodite (Venus de Milo)",
    "date_display": "",
    "date_sort": -150,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/7.greek late periods.roman_page8_img2.jpeg",
    "presentation": "7.greek late periods.roman",
    "page_number": ""
  },
  {
    "id": "7.greek late periods.roman_page_8_page8_img3",
    "title": "ALEXANDROS OF ANTIOCH-ON-THE-MEANDER, Aphrodite (Venus de Milo)",
    "date_display": "",
    "date_sort": -150,
    "description": "",
    "era": "Classical Antiquity",
    "image_path": "images/7.greek late periods.roman_page8_img3.jpeg",
    "presentation": "7.greek late periods.roman",
    "page_number": ""
  },
  {
    "id": "10.intro.medieval europe.renaissance beginnings_page_10_page10_img1",
    "title": "Chartres Cathedral, West fa\u00e7ade",
    "date_display": "1145-1155",
    "date_sort": 0,
    "description": "",
    "era": "High Renaissance",
    "image_path": "images/10.intro.medieval europe.renaissance beginnings_page10_img1.jpeg",
    "presentation": "10.intro.medieval europe.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "10.intro.medieval europe.renaissance beginnings_page_12_page12_img1",
    "title": "Central portal on the north transept, Chartres Cathedral",
    "date_display": "1204",
    "date_sort": 0,
    "description": "Chartres Cathedral",
    "era": "High Renaissance",
    "image_path": "images/10.intro.medieval europe.renaissance beginnings_page12_img1.jpeg",
    "presentation": "10.intro.medieval europe.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "10.intro.medieval europe.renaissance beginnings_page_16_page16_img1",
    "title": "Pisa Cathedral, bell-tower and Baptistery, next to the \u201dCamposanto\u201d graveyard",
    "date_display": "",
    "date_sort": 0,
    "description": "Pisa Cathedral",
    "era": "High Renaissance",
    "image_path": "images/10.intro.medieval europe.renaissance beginnings_page16_img1.jpeg",
    "presentation": "10.intro.medieval europe.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "10.intro.medieval europe.renaissance beginnings_page_17_page17_img2",
    "title": "Roman sarcophagus, relief: Phaedra and Hippolyte, 1st c. Burial sarcophagus of Biatrice of Lorraine, 11th century",
    "date_display": "1th century CE",
    "date_sort": 0,
    "description": "",
    "era": "Late Antiquity",
    "image_path": "images/10.intro.medieval europe.renaissance beginnings_page17_img2.jpeg",
    "presentation": "10.intro.medieval europe.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "11.renaissance beginnings_page_2_page2_img2",
    "title": "Roman sarcophagus, relief: Phaedra and Hippolyte, 1st c. Burial sarcophagus of Biatrice of Lorraine, 11th century",
    "date_display": "1th century CE",
    "date_sort": 0,
    "description": "",
    "era": "Late Antiquity",
    "image_path": "images/11.renaissance beginnings_page2_img2.jpeg",
    "presentation": "11.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "11.renaissance beginnings_page_2_page2_img1",
    "title": "Roman sarcophagus, relief: Phaedra and Hippolyte, 1st c. Burial sarcophagus of Biatrice of Lorraine, 11th century",
    "date_display": "1th century CE",
    "date_sort": 0,
    "description": "",
    "era": "Late Antiquity",
    "image_path": "images/11.renaissance beginnings_page2_img1.jpeg",
    "presentation": "11.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "11.renaissance beginnings_page_13_page13_img1",
    "title": "Arena Chapel",
    "date_display": "1305\u20131306",
    "date_sort": 0,
    "description": "Padua, Italy",
    "era": "High Renaissance",
    "image_path": "images/11.renaissance beginnings_page13_img1.jpeg",
    "presentation": "11.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "11.renaissance beginnings_page_14_page14_img1",
    "title": "Arena Chapel",
    "date_display": "1305-1306",
    "date_sort": 0,
    "description": "Padua, Italy",
    "era": "High Renaissance",
    "image_path": "images/11.renaissance beginnings_page14_img1.jpeg",
    "presentation": "11.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "11.renaissance beginnings_page_15_page15_img1",
    "title": "Arena Chapel",
    "date_display": "1305-1306",
    "date_sort": 0,
    "description": "Padua, Italy",
    "era": "High Renaissance",
    "image_path": "images/11.renaissance beginnings_page15_img1.jpeg",
    "presentation": "11.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "11.renaissance beginnings_page_15_page15_img2",
    "title": "Arena Chapel",
    "date_display": "1305-1306",
    "date_sort": 0,
    "description": "Padua, Italy",
    "era": "High Renaissance",
    "image_path": "images/11.renaissance beginnings_page15_img2.jpeg",
    "presentation": "11.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "7.greek late periods.roman_page_10_page10_img1",
    "title": "Colosseum (Flavian Amphitheater)",
    "date_display": "ca. 70-80 CE",
    "date_sort": 70,
    "description": "",
    "era": "Late Antiquity",
    "image_path": "images/7.greek late periods.roman_page10_img1.jpeg",
    "presentation": "7.greek late periods.roman",
    "page_number": ""
  },
  {
    "id": "8.roman.early christianity_page_8_page8_img1",
    "title": "Arch of Titus",
    "date_display": "81 CE",
    "date_sort": 81,
    "description": "",
    "era": "Late Antiquity",
    "image_path": "images/8.roman.early christianity_page8_img1.jpeg",
    "presentation": "8.roman.early christianity",
    "page_number": ""
  },
  {
    "id": "8.roman.early christianity_page_9_page9_img1",
    "title": "Spoils of Jerusalem, relief panel from the Arch of Titus, Rome, Italy, after 81 CE.",
    "date_display": "81 CE",
    "date_sort": 81,
    "description": "",
    "era": "Late Antiquity",
    "image_path": "images/8.roman.early christianity_page9_img1.jpeg",
    "presentation": "8.roman.early christianity",
    "page_number": ""
  },
  {
    "id": "8.roman.early christianity_page_10_page10_img1",
    "title": "Triumph of Titus, relief panel from the Arch of Titus, Rome, Italy, after 81 CE. Marble, approx. 2.16 meters high.",
    "date_display": "81 CE",
    "date_sort": 81,
    "description": "",
    "era": "Late Antiquity",
    "image_path": "images/8.roman.early christianity_page10_img1.jpeg",
    "presentation": "8.roman.early christianity",
    "page_number": ""
  },
  {
    "id": "8.roman.early christianity_page_11_page11_img1",
    "title": "The Pantheon, Rome, Italy, 118\u2013125 CE.",
    "date_display": "118-125 CE",
    "date_sort": 118,
    "description": "",
    "era": "Late Antiquity",
    "image_path": "images/8.roman.early christianity_page11_img1.jpeg",
    "presentation": "8.roman.early christianity",
    "page_number": ""
  },
  {
    "id": "8.roman.early christianity_page_11_page11_img2",
    "title": "The Pantheon, Rome, Italy, 118\u2013125 CE.",
    "date_display": "118-125 CE",
    "date_sort": 118,
    "description": "",
    "era": "Late Antiquity",
    "image_path": "images/8.roman.early christianity_page11_img2.jpeg",
    "presentation": "8.roman.early christianity",
    "page_number": ""
  },
  {
    "id": "8.roman.early christianity_page_22_page22_img1",
    "title": "Hadrian as lion hunter, 128- 138 AD, Arch of Constantine,",
    "date_display": "128-138 CE",
    "date_sort": 128,
    "description": "",
    "era": "Late Antiquity",
    "image_path": "images/8.roman.early christianity_page22_img1.jpeg",
    "presentation": "8.roman.early christianity",
    "page_number": ""
  },
  {
    "id": "8.roman.early christianity_page_15_page15_img1",
    "title": "Portraits of the four tetrarchs, from Constantinople, ca. 305 CE.",
    "date_display": "305 CE",
    "date_sort": 305,
    "description": "",
    "era": "Late Antiquity",
    "image_path": "images/8.roman.early christianity_page15_img1.jpeg",
    "presentation": "8.roman.early christianity",
    "page_number": ""
  },
  {
    "id": "8.roman.early christianity_page_19_page19_img1",
    "title": "Arch of Constantine, Rome, Italy, 312\u2013315 CE (south side).",
    "date_display": "312-315 CE",
    "date_sort": 312,
    "description": "",
    "era": "Late Antiquity",
    "image_path": "images/8.roman.early christianity_page19_img1.jpeg",
    "presentation": "8.roman.early christianity",
    "page_number": ""
  },
  {
    "id": "8.roman.early christianity_page_21_page21_img1",
    "title": "Distribution of largess, detail of the north frieze of the Arch of Constantine",
    "date_display": "312-315 CE",
    "date_sort": 312,
    "description": "Rome, Italy",
    "era": "Late Antiquity",
    "image_path": "images/8.roman.early christianity_page21_img1.jpeg",
    "presentation": "8.roman.early christianity",
    "page_number": ""
  },
  {
    "id": "8.roman.early christianity_page_22_page22_img2",
    "title": "Detail of the north frieze of the Arch of Constantine",
    "date_display": "312-315 CE",
    "date_sort": 312,
    "description": "",
    "era": "Late Antiquity",
    "image_path": "images/8.roman.early christianity_page22_img2.jpeg",
    "presentation": "8.roman.early christianity",
    "page_number": ""
  },
  {
    "id": "8.roman.early christianity_page_17_page17_img2",
    "title": "Portrait of Constantine",
    "date_display": "ca. 315-330 CE",
    "date_sort": 315,
    "description": "Basilica Nova, Rome",
    "era": "Late Antiquity",
    "image_path": "images/8.roman.early christianity_page17_img2.jpeg",
    "presentation": "8.roman.early christianity",
    "page_number": ""
  },
  {
    "id": "9.intro.medieval europe_page_4_page4_img1",
    "title": "Theodosius",
    "date_display": "379-395",
    "date_sort": 379,
    "description": "",
    "era": "Late Antiquity",
    "image_path": "images/9.intro.medieval europe_page4_img1.jpeg",
    "presentation": "9.intro.medieval europe",
    "page_number": ""
  },
  {
    "id": "9.intro.medieval europe_page_4_page4_img4",
    "title": "Arcadius, Emperor of the East, 383-408",
    "date_display": "383-408",
    "date_sort": 383,
    "description": "",
    "era": "Late Antiquity",
    "image_path": "images/9.intro.medieval europe_page4_img4.jpeg",
    "presentation": "9.intro.medieval europe",
    "page_number": ""
  },
  {
    "id": "9.intro.medieval europe_page_4_page4_img5",
    "title": "Honorius, Emperor of the West, 393-423",
    "date_display": "393-423",
    "date_sort": 393,
    "description": "",
    "era": "Late Antiquity",
    "image_path": "images/9.intro.medieval europe_page4_img5.jpeg",
    "presentation": "9.intro.medieval europe",
    "page_number": ""
  },
  {
    "id": "9.intro.medieval europe_page_30_page30_img2",
    "title": "Christ Pantocrator, encaustic on wood, 6th century, ,",
    "date_display": "6th century CE",
    "date_sort": 500,
    "description": "",
    "era": "Early Medieval",
    "image_path": "images/9.intro.medieval europe_page30_img2.jpeg",
    "presentation": "9.intro.medieval europe",
    "page_number": ""
  },
  {
    "id": "9.intro.medieval europe_page_31_page31_img2",
    "title": "Christ Pantocrator, encaustic on wood, 6th century, , Monastery of Saint Catherine",
    "date_display": "6th century CE",
    "date_sort": 500,
    "description": "",
    "era": "Early Medieval",
    "image_path": "images/9.intro.medieval europe_page31_img2.jpeg",
    "presentation": "9.intro.medieval europe",
    "page_number": ""
  },
  {
    "id": "9.intro.medieval europe_page_19_page19_img1",
    "title": "San Vitale",
    "date_display": "526-547",
    "date_sort": 526,
    "description": "Ravenna, Italy",
    "era": "Early Medieval",
    "image_path": "images/9.intro.medieval europe_page19_img1.jpeg",
    "presentation": "9.intro.medieval europe",
    "page_number": ""
  },
  {
    "id": "9.intro.medieval europe_page_20_page20_img2",
    "title": "Interior of San Vitale",
    "date_display": "526-537",
    "date_sort": 526,
    "description": "Ravenna, Italy",
    "era": "Early Medieval",
    "image_path": "images/9.intro.medieval europe_page20_img2.jpeg",
    "presentation": "9.intro.medieval europe",
    "page_number": ""
  },
  {
    "id": "9.intro.medieval europe_page_20_page20_img3",
    "title": "Interior of San Vitale",
    "date_display": "527-537",
    "date_sort": 526,
    "description": "Ravenna, Italy",
    "era": "Early Medieval",
    "image_path": "images/9.intro.medieval europe_page20_img3.jpeg",
    "presentation": "9.intro.medieval europe",
    "page_number": ""
  },
  {
    "id": "9.intro.medieval europe_page_7_page7_img1",
    "title": "NTHEMIUS OF TRALLES and ISIDORUS OF MILETUS, Hagia",
    "date_display": "532-537",
    "date_sort": 532,
    "description": "",
    "era": "Early Medieval",
    "image_path": "images/9.intro.medieval europe_page7_img1.jpeg",
    "presentation": "9.intro.medieval europe",
    "page_number": ""
  },
  {
    "id": "9.intro.medieval europe_page_9_page9_img1",
    "title": "NTHEMIUS OF TRALLES and ISIDORUS OF MILETUS, Hagia",
    "date_display": "",
    "date_sort": 532,
    "description": "",
    "era": "Early Medieval",
    "image_path": "images/9.intro.medieval europe_page9_img1.jpeg",
    "presentation": "9.intro.medieval europe",
    "page_number": ""
  },
  {
    "id": "9.intro.medieval europe_page_10_page10_img1",
    "title": "ANTHEMIUS OF TRALLES and ISIDORUS OF MILETUS, interior of Hagia Sophia",
    "date_display": "",
    "date_sort": 532,
    "description": "",
    "era": "Early Medieval",
    "image_path": "images/9.intro.medieval europe_page10_img1.jpeg",
    "presentation": "9.intro.medieval europe",
    "page_number": ""
  },
  {
    "id": "9.intro.medieval europe_page_12_page12_img1",
    "title": "ANTHEMIUS OF TRALLES and ISIDORUS OF MILETUS, interior of Hagia Sophia",
    "date_display": "",
    "date_sort": 532,
    "description": "",
    "era": "Early Medieval",
    "image_path": "images/9.intro.medieval europe_page12_img1.jpeg",
    "presentation": "9.intro.medieval europe",
    "page_number": ""
  },
  {
    "id": "9.intro.medieval europe_page_14_page14_img1",
    "title": "ANTHEMIUS OF TRALLES and ISIDORUS OF MILETUS, interior of Hagia Sophia",
    "date_display": "",
    "date_sort": 532,
    "description": "",
    "era": "Early Medieval",
    "image_path": "images/9.intro.medieval europe_page14_img1.jpeg",
    "presentation": "9.intro.medieval europe",
    "page_number": ""
  },
  {
    "id": "9.intro.medieval europe_page_16_page16_img1",
    "title": "ANTHEMIUS OF TRALLES and ISIDORUS OF MILETUS, interior of Hagia Sophia",
    "date_display": "532-537",
    "date_sort": 532,
    "description": "",
    "era": "Early Medieval",
    "image_path": "images/9.intro.medieval europe_page16_img1.jpeg",
    "presentation": "9.intro.medieval europe",
    "page_number": ""
  },
  {
    "id": "9.intro.medieval europe_page_25_page25_img1",
    "title": "Saint Apollinaris amid sheep - Sant\u2019Apollinare in  Classe",
    "date_display": "533 - 549",
    "date_sort": 533,
    "description": "Ravenna, Italy",
    "era": "Early Medieval",
    "image_path": "images/9.intro.medieval europe_page25_img1.jpeg",
    "presentation": "9.intro.medieval europe",
    "page_number": ""
  },
  {
    "id": "9.intro.medieval europe_page_27_page27_img1",
    "title": "Saint Apollinaris amid sheep, apse mosaic, Sant\u2019Apollinare in Classe",
    "date_display": "533 - 549",
    "date_sort": 533,
    "description": "Ravenna, Italy",
    "era": "Early Medieval",
    "image_path": "images/9.intro.medieval europe_page27_img1.jpeg",
    "presentation": "9.intro.medieval europe",
    "page_number": ""
  },
  {
    "id": "9.intro.medieval europe_page_21_page21_img1",
    "title": "Justinian, Bishop Maximianus, and attendants, mosaic from the north wall of the apse",
    "date_display": "ca. 547",
    "date_sort": 547,
    "description": "Ravenna, Italy",
    "era": "Early Medieval",
    "image_path": "images/9.intro.medieval europe_page21_img1.jpeg",
    "presentation": "9.intro.medieval europe",
    "page_number": ""
  },
  {
    "id": "9.intro.medieval europe_page_22_page22_img1",
    "title": "Justinian, Bishop Maximianus, and attendants, mosaic from the north wall of the apse, San Vitale",
    "date_display": "ca. 547",
    "date_sort": 547,
    "description": "Ravenna, Italy",
    "era": "Early Medieval",
    "image_path": "images/9.intro.medieval europe_page22_img1.jpeg",
    "presentation": "9.intro.medieval europe",
    "page_number": ""
  },
  {
    "id": "9.intro.medieval europe_page_23_page23_img1",
    "title": "Theodora and attendants, mosaic from the south wall of the  apse, San Vitale",
    "date_display": "ca. 547",
    "date_sort": 547,
    "description": "Ravenna, Italy",
    "era": "Early Medieval",
    "image_path": "images/9.intro.medieval europe_page23_img1.jpeg",
    "presentation": "9.intro.medieval europe",
    "page_number": ""
  },
  {
    "id": "9.intro.medieval europe_page_30_page30_img1",
    "title": "Virgin (Theotokos) and Child between Saints Theodore and George",
    "date_display": "6th or 7th century",
    "date_sort": 550,
    "description": "",
    "era": "Early Medieval",
    "image_path": "images/9.intro.medieval europe_page30_img1.jpeg",
    "presentation": "9.intro.medieval europe",
    "page_number": ""
  },
  {
    "id": "9.intro.medieval europe_page_31_page31_img1",
    "title": "Christ Pantocrator, apse mosaics, Monreale Cathedral, Sicily",
    "date_display": "12th century CE",
    "date_sort": 1100,
    "description": "",
    "era": "Medieval",
    "image_path": "images/9.intro.medieval europe_page31_img1.jpeg",
    "presentation": "9.intro.medieval europe",
    "page_number": ""
  },
  {
    "id": "10.intro.medieval europe.renaissance beginnings_page_3_page3_img1",
    "title": "St. Denis, Paris, 1135-40",
    "date_display": "1135 CE",
    "date_sort": 1135,
    "description": "",
    "era": "Medieval",
    "image_path": "images/10.intro.medieval europe.renaissance beginnings_page3_img1.jpeg",
    "presentation": "10.intro.medieval europe.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "10.intro.medieval europe.renaissance beginnings_page_3_page3_img2",
    "title": "St. Denis, Paris, 1135-40",
    "date_display": "1135 CE",
    "date_sort": 1135,
    "description": "",
    "era": "Medieval",
    "image_path": "images/10.intro.medieval europe.renaissance beginnings_page3_img2.jpeg",
    "presentation": "10.intro.medieval europe.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "10.intro.medieval europe.renaissance beginnings_page_8_page8_img1",
    "title": "Chartres Cathedral, West fa\u00e7ade, 1145-1155",
    "date_display": "1145-1155 CE",
    "date_sort": 1145,
    "description": "",
    "era": "Medieval",
    "image_path": "images/10.intro.medieval europe.renaissance beginnings_page8_img1.jpeg",
    "presentation": "10.intro.medieval europe.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "10.intro.medieval europe.renaissance beginnings_page_4_page4_img1",
    "title": "Chartre Cathedral, rebuilt after 1194, France",
    "date_display": "1194 CE",
    "date_sort": 1194,
    "description": "",
    "era": "Medieval",
    "image_path": "images/10.intro.medieval europe.renaissance beginnings_page4_img1.jpeg",
    "presentation": "10.intro.medieval europe.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "10.intro.medieval europe.renaissance beginnings_page_5_page5_img1",
    "title": "Interior view, Chartres Cathedral, after 1194, France",
    "date_display": "1194 CE",
    "date_sort": 1194,
    "description": "",
    "era": "Medieval",
    "image_path": "images/10.intro.medieval europe.renaissance beginnings_page5_img1.jpeg",
    "presentation": "10.intro.medieval europe.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "1.bezalel.intro 2026_page_3_page3_img3",
    "title": "Medieval art 13th century Classical",
    "date_display": "13th century CE",
    "date_sort": 1200,
    "description": "",
    "era": "Medieval",
    "image_path": "images/1.bezalel.intro 2026_page3_img3.jpeg",
    "presentation": "1.bezalel.intro 2026",
    "page_number": ""
  },
  {
    "id": "10.intro.medieval europe.renaissance beginnings_page_11_page11_img1",
    "title": "Central portal on the north transept, 1204, Chartres Cathedral,",
    "date_display": "1204 CE",
    "date_sort": 1204,
    "description": "",
    "era": "Medieval",
    "image_path": "images/10.intro.medieval europe.renaissance beginnings_page11_img1.jpeg",
    "presentation": "10.intro.medieval europe.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "10.intro.medieval europe.renaissance beginnings_page_11_page11_img2",
    "title": "Central portal on the north transept, 1204, Chartres Cathedral,",
    "date_display": "1204 CE",
    "date_sort": 1204,
    "description": "",
    "era": "Medieval",
    "image_path": "images/10.intro.medieval europe.renaissance beginnings_page11_img2.jpeg",
    "presentation": "10.intro.medieval europe.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "10.intro.medieval europe.renaissance beginnings_page_13_page13_img2",
    "title": "Chartres, rosette window above lancet windows, West fa\u00e7ade, 1215",
    "date_display": "1215 CE",
    "date_sort": 1215,
    "description": "",
    "era": "Medieval",
    "image_path": "images/10.intro.medieval europe.renaissance beginnings_page13_img2.jpeg",
    "presentation": "10.intro.medieval europe.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "10.intro.medieval europe.renaissance beginnings_page_13_page13_img1",
    "title": "Chartres Cathedral, Chartres, France, ca. 1220.",
    "date_display": "1220 CE",
    "date_sort": 1220,
    "description": "",
    "era": "Medieval",
    "image_path": "images/10.intro.medieval europe.renaissance beginnings_page13_img1.jpeg",
    "presentation": "10.intro.medieval europe.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "10.intro.medieval europe.renaissance beginnings_page_15_page15_img1",
    "title": "Francis Altarpiece, San Francesco, Pescia, Italy, 1235. Tempera on wood",
    "date_display": "1235 CE",
    "date_sort": 1235,
    "description": "",
    "era": "Medieval",
    "image_path": "images/10.intro.medieval europe.renaissance beginnings_page15_img1.jpeg",
    "presentation": "10.intro.medieval europe.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "10.intro.medieval europe.renaissance beginnings_page_18_page18_img2",
    "title": "NICOLA PISANO, pulpit of Pisa Cathedral baptistery, Pisa, Italy, 1259\u20131260. Marble.",
    "date_display": "1259-1260 CE",
    "date_sort": 1259,
    "description": "",
    "era": "Medieval",
    "image_path": "images/10.intro.medieval europe.renaissance beginnings_page18_img2.jpeg",
    "presentation": "10.intro.medieval europe.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "10.intro.medieval europe.renaissance beginnings_page_18_page18_img1",
    "title": "NICOLA PISANO, pulpit of Pisa Cathedral baptistery, Pisa, Italy, 1259\u20131260. Marble.",
    "date_display": "1259-1260 CE",
    "date_sort": 1259,
    "description": "",
    "era": "Medieval",
    "image_path": "images/10.intro.medieval europe.renaissance beginnings_page18_img1.jpeg",
    "presentation": "10.intro.medieval europe.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "11.renaissance beginnings_page_3_page3_img2",
    "title": "NICOLA PISANO, pulpit of Pisa Cathedral baptistery, Pisa, Italy, 1259\u20131260. Marble.",
    "date_display": "1259-1260 CE",
    "date_sort": 1259,
    "description": "",
    "era": "Medieval",
    "image_path": "images/11.renaissance beginnings_page3_img2.jpeg",
    "presentation": "11.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "11.renaissance beginnings_page_3_page3_img1",
    "title": "NICOLA PISANO, pulpit of Pisa Cathedral baptistery, Pisa, Italy, 1259\u20131260. Marble.",
    "date_display": "1259-1260 CE",
    "date_sort": 1259,
    "description": "",
    "era": "Medieval",
    "image_path": "images/11.renaissance beginnings_page3_img1.jpeg",
    "presentation": "11.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "11.renaissance beginnings_page_4_page4_img1",
    "title": "NICOLA PISANO, The Annunciation and the Nativity, detail of Pisa baptistery pulpit, Pisa, Italy, 1259\u20131260. Marble relief.",
    "date_display": "1259-1260 CE",
    "date_sort": 1259,
    "description": "",
    "era": "Medieval",
    "image_path": "images/11.renaissance beginnings_page4_img1.jpeg",
    "presentation": "11.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "11.renaissance beginnings_page_5_page5_img1",
    "title": "Nicola Pisano, Adoration of the Magi, detail of Pisa baptistery pulpit, Pisa, Italy, 1259\u20131260. Marble relief.",
    "date_display": "1259-1260 CE",
    "date_sort": 1259,
    "description": "",
    "era": "Medieval",
    "image_path": "images/11.renaissance beginnings_page5_img1.jpeg",
    "presentation": "11.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "11.renaissance beginnings_page_11_page11_img1",
    "title": "CIMABUE, Madonna Enthroned with Angels and Prophets, ca. 1280\u20131290.",
    "date_display": "1280-1290 CE",
    "date_sort": 1280,
    "description": "",
    "era": "Medieval",
    "image_path": "images/11.renaissance beginnings_page11_img1.jpeg",
    "presentation": "11.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "11.renaissance beginnings_page_10_page10_img2",
    "title": "CIMABUE, Crucifix, 1287-88, Panel, 448 x",
    "date_display": "1287 CE",
    "date_sort": 1287,
    "description": "",
    "era": "Medieval",
    "image_path": "images/11.renaissance beginnings_page10_img2.jpeg",
    "presentation": "11.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "11.renaissance beginnings_page_10_page10_img1",
    "title": "GIOTTO di Bondone, Crucifix. 1290-1300,",
    "date_display": "1290-1300 CE",
    "date_sort": 1290,
    "description": "",
    "era": "Medieval",
    "image_path": "images/11.renaissance beginnings_page10_img1.jpeg",
    "presentation": "11.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "12.renaissance.intro_page_5_page5_img1",
    "title": "ARNOLFO DI CAMBIO and others, Florence Cathedral (view from the south), Florence, Italy, begun 1296.",
    "date_display": "1296 CE",
    "date_sort": 1296,
    "description": "",
    "era": "Medieval",
    "image_path": "images/12.renaissance.intro_page5_img1.jpeg",
    "presentation": "12.renaissance.intro",
    "page_number": ""
  },
  {
    "id": "11.renaissance beginnings_page_12_page12_img1",
    "title": "Padua, Italy, 1305\u20131306.",
    "date_display": "1305-1306 CE",
    "date_sort": 1305,
    "description": "",
    "era": "Early Renaissance",
    "image_path": "images/11.renaissance beginnings_page12_img1.jpeg",
    "presentation": "11.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "11.renaissance beginnings_page_12_page12_img2",
    "title": "Padua, Italy, 1305\u20131306.",
    "date_display": "1305-1306 CE",
    "date_sort": 1305,
    "description": "",
    "era": "Early Renaissance",
    "image_path": "images/11.renaissance beginnings_page12_img2.jpeg",
    "presentation": "11.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "11.renaissance beginnings_page_11_page11_img2",
    "title": "GIOTTO DI BONDONE, Madonna Enthroned, ca. 1310. Tempera on",
    "date_display": "1310 CE",
    "date_sort": 1310,
    "description": "",
    "era": "Early Renaissance",
    "image_path": "images/11.renaissance beginnings_page11_img2.jpeg",
    "presentation": "11.renaissance beginnings",
    "page_number": ""
  },
  {
    "id": "12.renaissance.intro_page_6_page6_img1",
    "title": "Santa Maria del Fiore in a painting by Andrea di Bonaiuto, 1360",
    "date_display": "1360 CE",
    "date_sort": 1360,
    "description": "",
    "era": "Early Renaissance",
    "image_path": "images/12.renaissance.intro_page6_img1.jpeg",
    "presentation": "12.renaissance.intro",
    "page_number": ""
  },
  {
    "id": "12.renaissance.intro_page_7_page7_img2",
    "title": "Nanni di Banco, Isaia, 1408, Forence, Museo",
    "date_display": "1408 CE",
    "date_sort": 1408,
    "description": "",
    "era": "Early Renaissance",
    "image_path": "images/12.renaissance.intro_page7_img2.jpeg",
    "presentation": "12.renaissance.intro",
    "page_number": ""
  },
  {
    "id": "12.renaissance.intro_page_7_page7_img1",
    "title": "Donatello, David, 1409, Florence,",
    "date_display": "1409 CE",
    "date_sort": 1409,
    "description": "",
    "era": "Early Renaissance",
    "image_path": "images/12.renaissance.intro_page7_img1.jpeg",
    "presentation": "12.renaissance.intro",
    "page_number": ""
  },
  {
    "id": "9.intro.medieval europe_page_29_page29_img1",
    "title": "Master of Saint Veronica, Saint Veronica with the Holy Kerchief",
    "date_display": "1420 CE",
    "date_sort": 1420,
    "description": "",
    "era": "Early Renaissance",
    "image_path": "images/9.intro.medieval europe_page29_img1.jpeg",
    "presentation": "9.intro.medieval europe",
    "page_number": ""
  },
  {
    "id": "12.renaissance.intro_page_13_page13_img1",
    "title": "Florence, Italy, ca. 1428. Fresco.",
    "date_display": "1428 CE",
    "date_sort": 1428,
    "description": "",
    "era": "Early Renaissance",
    "image_path": "images/12.renaissance.intro_page13_img1.jpeg",
    "presentation": "12.renaissance.intro",
    "page_number": ""
  },
  {
    "id": "12.renaissance.intro_page_13_page13_img2",
    "title": "Florence, Italy, ca. 1428. Fresco.",
    "date_display": "1428 CE",
    "date_sort": 1428,
    "description": "",
    "era": "Early Renaissance",
    "image_path": "images/12.renaissance.intro_page13_img2.jpeg",
    "presentation": "12.renaissance.intro",
    "page_number": ""
  },
  {
    "id": "12.renaissance.intro_page_15_page15_img1",
    "title": "Florence, Italy, ca. 1428. Fresco.",
    "date_display": "1428 CE",
    "date_sort": 1428,
    "description": "",
    "era": "Early Renaissance",
    "image_path": "images/12.renaissance.intro_page15_img1.jpeg",
    "presentation": "12.renaissance.intro",
    "page_number": ""
  },
  {
    "id": "12.renaissance.intro_page_15_page15_img2",
    "title": "Florence, Italy, ca. 1428. Fresco.",
    "date_display": "1428 CE",
    "date_sort": 1428,
    "description": "",
    "era": "Early Renaissance",
    "image_path": "images/12.renaissance.intro_page15_img2.jpeg",
    "presentation": "12.renaissance.intro",
    "page_number": ""
  },
  {
    "id": "12.renaissance.intro_page_16_page16_img1",
    "title": "Lamentation, 1480,",
    "date_display": "1480 CE",
    "date_sort": 1480,
    "description": "",
    "era": "Early Renaissance",
    "image_path": "images/12.renaissance.intro_page16_img1.jpeg",
    "presentation": "12.renaissance.intro",
    "page_number": ""
  },
  {
    "id": "12.renaissance.intro_page_19_page19_img1",
    "title": "Domenicho Ghirlandaio, The Last Supper, 1480, fresco, Ognissanti, Florence",
    "date_display": "1480 CE",
    "date_sort": 1480,
    "description": "",
    "era": "Early Renaissance",
    "image_path": "images/12.renaissance.intro_page19_img1.jpeg",
    "presentation": "12.renaissance.intro",
    "page_number": ""
  },
  {
    "id": "1.bezalel.intro 2026_page_6_page6_img1",
    "title": "Hans Memling, Man with a Letter, 1485/89",
    "date_display": "1485 CE",
    "date_sort": 1485,
    "description": "",
    "era": "Early Renaissance",
    "image_path": "images/1.bezalel.intro 2026_page6_img1.jpeg",
    "presentation": "1.bezalel.intro 2026",
    "page_number": ""
  },
  {
    "id": "1.bezalel.intro 2026_page_8_page8_img1",
    "title": "Leonardo da Vinci, The Last Supper, 1495-1498, Santa Maria della Grazie, Milan",
    "date_display": "1495-1498 CE",
    "date_sort": 1495,
    "description": "",
    "era": "Early Renaissance",
    "image_path": "images/1.bezalel.intro 2026_page8_img1.jpeg",
    "presentation": "1.bezalel.intro 2026",
    "page_number": ""
  },
  {
    "id": "12.renaissance.intro_page_17_page17_img1",
    "title": "Supper (cleaned), ca. 1495\u20131498. Fresco (oil and tempera on plaster),",
    "date_display": "1495-1498 CE",
    "date_sort": 1495,
    "description": "",
    "era": "Early Renaissance",
    "image_path": "images/12.renaissance.intro_page17_img1.jpeg",
    "presentation": "12.renaissance.intro",
    "page_number": ""
  },
  {
    "id": "1.bezalel.intro 2026_page_5_page5_img1",
    "title": "Michelangelo, Pieta, 1498-99,",
    "date_display": "1498 CE",
    "date_sort": 1498,
    "description": "",
    "era": "Early Renaissance",
    "image_path": "images/1.bezalel.intro 2026_page5_img1.jpeg",
    "presentation": "1.bezalel.intro 2026",
    "page_number": ""
  },
  {
    "id": "12.renaissance.intro_page_8_page8_img1",
    "title": "MICHELANGELO BUONARROTI, David, 1501\u20131504. Marble,. Galleria",
    "date_display": "1501-1504 CE",
    "date_sort": 1501,
    "description": "",
    "era": "High Renaissance",
    "image_path": "images/12.renaissance.intro_page8_img1.jpeg",
    "presentation": "12.renaissance.intro",
    "page_number": ""
  },
  {
    "id": "4.bezalel.intro.mesopotamian.egyptian 2026_page_3_page3_img1",
    "title": "Rosetta Stone, 196 BC, discovered 1799, British",
    "date_display": "1799 CE",
    "date_sort": 1799,
    "description": "",
    "era": "Baroque & Rococo",
    "image_path": "images/4.bezalel.intro.mesopotamian.egyptian 2026_page3_img1.jpeg",
    "presentation": "4.bezalel.intro.mesopotamian.egyptian 2026",
    "page_number": ""
  },
  {
    "id": "1.bezalel.intro 2026_page_4_page4_img1",
    "title": "Manet, Olympia, 1863, Mus\u00e9e d\u2019Orsay",
    "date_display": "1863 CE",
    "date_sort": 1863,
    "description": "",
    "era": "19th Century",
    "image_path": "images/1.bezalel.intro 2026_page4_img1.jpeg",
    "presentation": "1.bezalel.intro 2026",
    "page_number": ""
  },
  {
    "id": "1.bezalel.intro 2026_page_9_page9_img1",
    "title": "Niki de saint Phalle, Venus of Milo, 1962",
    "date_display": "1962 CE",
    "date_sort": 1962,
    "description": "",
    "era": "Modern",
    "image_path": "images/1.bezalel.intro 2026_page9_img1.jpeg",
    "presentation": "1.bezalel.intro 2026",
    "page_number": ""
  },
  {
    "id": "1.bezalel.intro 2026_page_5_page5_img2",
    "title": "Renee Cox, Yo Mama\u2019s Pieta, 1996",
    "date_display": "1996 CE",
    "date_sort": 1996,
    "description": "",
    "era": "Modern",
    "image_path": "images/1.bezalel.intro 2026_page5_img2.jpeg",
    "presentation": "1.bezalel.intro 2026",
    "page_number": ""
  },
  {
    "id": "12.renaissance.intro_page_20_page20_img1",
    "title": "Rene Cox, Yo Mama\u2019s Last Supper",
    "date_display": "1996 CE",
    "date_sort": 1996,
    "description": "",
    "era": "Modern",
    "image_path": "images/12.renaissance.intro_page20_img1.jpeg",
    "presentation": "12.renaissance.intro",
    "page_number": ""
  },
  {
    "id": "12.renaissance.intro_page_20_page20_img2",
    "title": "Adi Ness, The Last Supper,",
    "date_display": "1996 CE",
    "date_sort": 1996,
    "description": "",
    "era": "Modern",
    "image_path": "images/12.renaissance.intro_page20_img2.jpeg",
    "presentation": "12.renaissance.intro",
    "page_number": ""
  },
  {
    "id": "1.bezalel.intro 2026_page_7_page7_img1",
    "title": "Adi Nes, The Last Supper, 1999",
    "date_display": "1999 CE",
    "date_sort": 1999,
    "description": "",
    "era": "Modern",
    "image_path": "images/1.bezalel.intro 2026_page7_img1.jpeg",
    "presentation": "1.bezalel.intro 2026",
    "page_number": ""
  }
];

const STATS = {
  "total_items": 179,
  "eras": {
    "Ancient Near East & Egypt": 45,
    "Medieval": 22,
    "Classical Antiquity": 33,
    "19th Century": 1,
    "Modern": 5,
    "Early Renaissance": 17,
    "High Renaissance": 11,
    "Late Antiquity": 18,
    "Prehistoric": 9,
    "Baroque & Rococo": 1,
    "Early Medieval": 17
  }
};

const PRESENTATIONS = [
  { name: "1. Bezalel Intro 2026", filename: "1.bezalel.intro 2026.pdf" },
  { name: "2. From the Caves to Civilization", filename: "2.bezalel.intro.from the caves to civilization 2026.pdf" },
  { name: "3. Mesopotamian & Egyptian Art", filename: "3.bezalel.intro.mesopotamian.egyptian 2026.pdf" },
  { name: "4. Mesopotamian & Egyptian Art (cont.)", filename: "4.bezalel.intro.mesopotamian.egyptian 2026.pdf" },
  { name: "5. Greek Art & Mimesis", filename: "5.intro.greek art.memesis.pdf" },
  { name: "6. Greek Art & Mimesis (cont.)", filename: "6.intro.greek art.memesis.pdf" },
  { name: "7. Greek Late Periods & Roman", filename: "7.greek late periods.roman.pdf" },
  { name: "8. Roman & Early Christianity", filename: "8.roman.early christianity.pdf" },
  { name: "9. Medieval Europe", filename: "9.intro.medieval europe.pdf" },
  { name: "10. Medieval Europe & Renaissance Beginnings", filename: "10.intro.medieval europe.renaissance beginnings.pdf" },
  { name: "11. Renaissance Beginnings", filename: "11.renaissance beginnings.pdf" },
  { name: "12. Renaissance Introduction", filename: "12.renaissance.intro.pdf" }
];
